[[items]]
title = "Reference"
href = "/reference/public-cli/"
level = 0
group = true

[[items]]
title = "Public CLI"
href = "/reference/public-cli/"
level = 1

[[items]]
title = "Admin CLI"
href = "/reference/admin-cli/"
level = 1

[[items]]
title = "CLI Workflows"
href = "/reference/cli-workflows/"
level = 1

[[items]]
title = "Authorisation Actions and Resources"
href = "/reference/authorisation-actions-and-resources/"
level = 1

[[items]]
title = "Index Definitions and Query JSON"
href = "/reference/index-definitions-and-query-json/"
level = 1
