#![recursion_limit = "512"]

use crate::auth::JwtManager;
use crate::config::Config;
use anyhow::Result;
use cluster::ClusterState;
use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;
use tokio::sync::{Mutex, RwLock, broadcast};

pub(crate) fn emit_test_timing(label: impl AsRef<str>, elapsed: Duration) {
    let label = label.as_ref();
    if std::env::var("ANVIL_TEST_TIMINGS").is_ok_and(|value| {
        matches!(
            value.trim().to_ascii_lowercase().as_str(),
            "1" | "true" | "yes" | "on"
        )
    }) {
        eprintln!("[timing] {label}={elapsed:?}");
    }
    if crate::perf::enabled() {
        crate::perf::record_duration("anvil_internal_span", &[("span", label)], elapsed);
    }
}

// The modules we've created
pub mod access_control;
pub mod anvil_personaldb_sqlite_changeset;
pub mod auth;
pub(crate) mod authz_coremeta_payload;
pub mod authz_derived_lag_watch;
pub mod authz_journal;
pub mod authz_namespace_watch;
pub mod authz_realm_schema;
pub mod authz_repair;
pub mod authz_schema;
pub mod authz_scope;
pub mod authz_segment;
pub mod authz_userset_index;
pub mod bucket_journal;
pub mod bucket_manager;
pub mod cache;
pub mod cluster;
pub mod cluster_identity;
pub mod config;
pub mod control_journal;
pub mod core_store;
pub mod crypto;
pub mod derived_index_catchup;
pub mod derived_index_proof;
pub mod diagnostic_store;
pub mod directory_repair;
pub mod discovery;
pub mod embedding_provider;
pub mod error_codes;
pub mod formats;
pub mod full_text_segment;
pub mod gateway_store;
pub mod git_pack;
pub mod git_source_index;
pub mod git_source_manifest;
pub mod git_source_query;
pub mod git_source_watch;
pub mod hf_journal;
pub mod index_builder;
pub mod index_coremeta;
pub mod index_diagnostic_journal;
pub mod index_journal;
pub mod index_partition_watch;
pub mod index_repair;
pub mod manifest_journal;
pub mod media_extraction;
pub mod mesh_control_segment;
pub mod mesh_control_stream;
pub mod mesh_directory;
pub mod mesh_lifecycle;
pub mod metadata_journal;
pub mod middleware;
pub mod model_journal;
pub mod multipart_journal;
pub mod native_idempotency;
pub mod object_links;
pub mod object_manager;
pub mod observability;
pub mod partition_fence;
pub mod perf;
pub mod perf_baseline;
pub mod permissions;
pub mod persistence;
pub mod personaldb_catchup;
pub mod personaldb_commit_store;
pub mod personaldb_control;
pub mod personaldb_coremeta;
pub mod personaldb_envelope;
pub mod personaldb_heads;
pub mod personaldb_projection;
pub mod personaldb_projection_builder;
pub mod personaldb_projection_writeback;
pub mod personaldb_repair;
pub mod personaldb_row_index;
pub mod personaldb_schema;
pub mod personaldb_segment;
pub mod personaldb_snapshot_builder;
pub mod personaldb_snapshot_store;
pub mod personaldb_submit;
pub mod personaldb_watch;
pub mod placement;
pub mod query_planner;
pub mod registry_segment;
pub mod repair_finding;
pub mod routing;
pub mod search_query;
pub mod services;
pub mod sharding;
pub mod storage;
pub mod system_realm;
pub mod task_journal;
pub mod task_lease;
pub mod tasks;
pub mod tenant_audit;
pub mod typed_field_segment;
pub mod validation;
pub mod vector_hnsw;
pub mod vector_segment;
pub mod watch_checkpoint;
pub mod watch_log;
pub mod watch_resume;
pub mod worker;
pub mod writer_segment_catalog;
pub mod writer_segment_range;

// The gRPC code generated by tonic-build
pub mod admin_audit;
pub mod append_journal;
pub mod anvil_api {
    tonic::include_proto!("anvil");
}

// Our application state, which will hold the persistence layer, storage engine, etc.
#[derive(Clone, Debug)]
pub struct AppState {
    pub persistence: persistence::Persistence,
    pub storage: storage::Storage,
    pub core_store: core_store::CoreStore,
    pub cluster: ClusterState,
    pub sharder: sharding::ShardManager,
    pub placer: placement::PlacementManager,
    pub jwt_manager: Arc<JwtManager>,
    pub region: String,
    pub bucket_manager: bucket_manager::BucketManager,
    pub object_manager: object_manager::ObjectManager,
    pub config: Arc<Config>,
    pub secret_keyring: Arc<crypto::EncryptionKeyring>,
    pub bucket_watch_tx: broadcast::Sender<persistence::BucketMetadataEvent>,
    pub authz_watch_tx: broadcast::Sender<persistence::AuthzTupleRecord>,
    pub index_watch_tx: broadcast::Sender<persistence::IndexDefinitionEvent>,
    pub personaldb_watch_tx: broadcast::Sender<personaldb_watch::PersonalDbGroupWatchEvent>,
    pub personaldb_projection_watch_tx:
        broadcast::Sender<personaldb_watch::PersonalDbProjectionWatchEvent>,
    pub personaldb_commit_locks: Arc<Mutex<HashMap<String, Arc<Mutex<()>>>>>,
    pub native_mutation_locks: Arc<Mutex<HashMap<String, Arc<Mutex<()>>>>>,
    pub observability: observability::Observability,
}

impl AppState {
    pub async fn new(
        config: Config,
        event_publisher: Option<tokio::sync::mpsc::Sender<cluster::MetadataEvent>>,
    ) -> Result<Self> {
        let config = config.with_persisted_identity().await?;
        let secret_keyring = Arc::new(config.secret_keyring()?);
        let partition_signing_key = hex::decode(&config.anvil_secret_encryption_key)?;
        let arc_config = Arc::new(config);
        let jwt_manager = Arc::new(JwtManager::new(arc_config.jwt_secret.clone()));
        let storage = storage::Storage::new_at(&arc_config.storage_path).await?;
        let core_store = core_store::CoreStore::new_with_pipeline_keyring_and_identity(
            storage.clone(),
            arc_config.core_pipeline_keyring()?,
            core_store::CoreStoreNodeIdentity {
                mesh_id: arc_config.mesh_id.clone(),
                node_id: arc_config.node_id.clone(),
                region_id: arc_config.region.clone(),
                cell_id: arc_config.cell_id.clone(),
                public_api_addr: arc_config.public_api_addr.clone(),
                internal_bearer_token: (!arc_config.corestore_internal_bearer_token.is_empty())
                    .then(|| arc_config.corestore_internal_bearer_token.clone()),
            },
        )
        .await?;
        let cluster_state = Arc::new(RwLock::new(HashMap::new()));
        let persistence = persistence::Persistence::new(&arc_config, event_publisher)?;
        if !arc_config.region.is_empty() {
            persistence.create_region(&arc_config.region).await?;
        }
        let sharder = sharding::ShardManager::new();
        let placer = placement::PlacementManager::default();
        let (object_watch_tx, _object_watch_rx) = tokio::sync::broadcast::channel(1024);
        let (bucket_watch_tx, _bucket_watch_rx) = tokio::sync::broadcast::channel(1024);
        let (authz_watch_tx, _authz_watch_rx) = tokio::sync::broadcast::channel(1024);
        let (index_watch_tx, _index_watch_rx) = tokio::sync::broadcast::channel(1024);
        let (personaldb_watch_tx, _personaldb_watch_rx) = tokio::sync::broadcast::channel(1024);
        let (personaldb_projection_watch_tx, _personaldb_projection_watch_rx) =
            tokio::sync::broadcast::channel(1024);
        let personaldb_commit_locks = Arc::new(Mutex::new(HashMap::new()));
        let native_mutation_locks = Arc::new(Mutex::new(HashMap::new()));
        let observability = observability::Observability::default();

        let bucket_manager =
            bucket_manager::BucketManager::new(persistence.clone(), storage.clone());
        let object_manager = object_manager::ObjectManager::new(
            persistence.clone(),
            storage.clone(),
            core_store.clone(),
            arc_config.region.clone(),
            arc_config.cross_region_routing_policy,
            partition_signing_key,
            object_watch_tx,
            observability.clone(),
        );
        system_realm::ensure_bootstrapped(
            &arc_config,
            &persistence,
            &storage,
            secret_keyring.as_ref(),
        )
        .await?;

        Ok(Self {
            persistence,
            storage,
            core_store,
            cluster: cluster_state,
            sharder,
            placer,
            jwt_manager,
            region: arc_config.region.clone(),
            bucket_manager,
            object_manager,
            config: arc_config,
            secret_keyring,
            bucket_watch_tx,
            authz_watch_tx,
            index_watch_tx,
            personaldb_watch_tx,
            personaldb_projection_watch_tx,
            personaldb_commit_locks,
            native_mutation_locks,
            observability,
        })
    }
}
