#![recursion_limit = "512"]

use crate::auth::JwtManager;
use crate::config::Config;
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::sync::{Arc, Weak};
use std::time::Duration;
use tokio::sync::Mutex;
use tracing::warn;

pub(crate) fn emit_test_timing(label: impl AsRef<str>, elapsed: Duration) {
    let label = label.as_ref();
    if std::env::var("ANVIL_TEST_TIMINGS").is_ok_and(|value| {
        matches!(
            value.trim().to_ascii_lowercase().as_str(),
            "1" | "true" | "yes" | "on"
        )
    }) {
        eprintln!("[timing] {label}={elapsed:?}");
    }
    if crate::perf::enabled() {
        crate::perf::record_duration("anvil_internal_span", &[("span", label)], elapsed);
    }
}

// The modules we've created
pub mod access_control;
pub mod anvil_personaldb_sqlite_changeset;
pub mod auth;
pub(crate) mod authz_coremeta_payload;
pub mod authz_derived_lag_watch;
mod authz_head;
pub mod authz_journal;
pub mod authz_namespace_watch;
pub mod authz_realm_schema;
pub mod authz_repair;
pub mod authz_schema;
pub mod authz_schema_contract;
pub mod authz_scope;
pub mod authz_segment;
pub mod authz_userset_index;
pub mod bucket_journal;
pub mod bucket_manager;
pub mod config;
pub mod control_journal;
pub mod core_store;
pub mod crypto;
pub mod derived_index_catchup;
pub mod derived_index_proof;
pub mod diagnostic_store;
pub mod directory_repair;
pub mod discovery;
pub mod embedding_provider;
pub mod error_codes;
pub mod formats;
pub mod full_text_segment;
pub mod gateway_store;
pub mod git_pack;
pub mod git_source_index;
pub mod git_source_manifest;
pub mod git_source_query;
pub mod git_source_watch;
pub mod hf_journal;
pub mod index_builder;
pub mod index_coremeta;
pub mod index_diagnostic_journal;
pub mod index_journal;
pub mod index_partition_watch;
pub mod index_repair;
pub mod manifest_journal;
pub mod media_extraction;
pub mod mesh_control_segment;
pub mod mesh_control_stream;
pub mod mesh_directory;
pub mod mesh_lifecycle;
pub mod metadata_journal;
pub mod middleware;
pub mod model_journal;
pub mod multipart_journal;
pub mod native_idempotency;
pub mod node_identity;
pub mod node_signing;
pub mod object_links;
pub mod object_manager;
pub mod observability;
pub mod partition_fence;
pub mod perf;
pub mod perf_baseline;
pub mod permissions;
pub mod persistence;
pub mod personaldb_catchup;
pub mod personaldb_commit_store;
pub mod personaldb_control;
pub mod personaldb_coremeta;
pub mod personaldb_envelope;
pub mod personaldb_heads;
pub mod personaldb_projection;
pub mod personaldb_projection_builder;
pub mod personaldb_projection_writeback;
pub mod personaldb_proposal_admission;
pub mod personaldb_repair;
pub mod personaldb_row_index;
pub mod personaldb_schema;
pub mod personaldb_segment;
pub mod personaldb_signing;
pub mod personaldb_signing_object;
pub mod personaldb_signing_store;
pub mod personaldb_snapshot_builder;
pub mod personaldb_snapshot_store;
pub mod personaldb_submit;
pub mod personaldb_watch;
pub mod query_planner;
pub mod registry_segment;
pub mod repair_finding;
pub mod routing;
pub mod search_query;
pub mod services;
pub mod sharding;
pub mod storage;
pub mod system_realm;
pub(crate) mod task_execution_guard;
pub mod task_journal;
pub mod task_lease;
pub mod tasks;
pub mod tenant_audit;
pub mod typed_field_segment;
pub mod validation;
pub mod vector_hnsw;
pub mod vector_segment;
pub mod watch_checkpoint;
pub mod watch_log;
pub mod watch_resume;
pub mod worker;
pub mod writer_segment_catalog;
pub mod writer_segment_range;

#[cfg(test)]
pub(crate) mod test_support;

// The gRPC code generated by tonic-build
pub mod admin_audit;
pub mod append_journal;
pub mod anvil_api {
    tonic::include_proto!("anvil");
}

// Our application state, which will hold the persistence layer, storage engine, etc.
#[derive(Clone, Debug)]
pub struct AppState {
    pub persistence: persistence::Persistence,
    pub storage: storage::Storage,
    pub core_store: core_store::CoreStore,
    pub sharder: sharding::ShardManager,
    pub jwt_manager: Arc<JwtManager>,
    pub region: String,
    pub bucket_manager: bucket_manager::BucketManager,
    pub object_manager: object_manager::ObjectManager,
    pub config: Arc<Config>,
    pub secret_keyring: Arc<crypto::EncryptionKeyring>,
    pub personaldb_signing_key_store: Arc<personaldb_signing_store::PersonalDbSigningKeyStore>,
    pub personaldb_protocol_keyring: Arc<personaldb_signing::PersonalDbProtocolKeyring>,
    pub personaldb_commit_locks: Arc<Mutex<HashMap<String, Weak<Mutex<()>>>>>,
    pub native_mutation_locks: Arc<Mutex<HashMap<String, Weak<Mutex<()>>>>>,
    pub observability: observability::Observability,
}

impl AppState {
    pub async fn new(
        config: Config,
        personaldb_protocol_keyring: personaldb_signing::PersonalDbProtocolKeyring,
    ) -> Result<Self> {
        let config = config.with_persisted_identity().await?;
        let secret_keyring = Arc::new(config.secret_keyring()?);
        let has_personaldb_keyring_override = personaldb_protocol_keyring.is_enabled()
            || !personaldb_protocol_keyring.trust_store().is_empty();
        let partition_signing_key = hex::decode(&config.anvil_secret_encryption_key)?;
        let arc_config = Arc::new(config);
        let jwt_manager = Arc::new(JwtManager::new(arc_config.jwt_secret.clone()));
        let storage = storage::Storage::new_at(&arc_config.storage_path).await?;
        let core_store = core_store::CoreStore::new_with_pipeline_keyring_and_identity(
            storage.clone(),
            arc_config.core_pipeline_keyring()?,
            core_store::CoreStoreNodeIdentity {
                mesh_id: arc_config.mesh_id.clone(),
                node_id: arc_config.node_id.clone(),
                region_id: arc_config.region.clone(),
                cell_id: arc_config.cell_id.clone(),
                public_api_addr: arc_config.public_api_addr.clone(),
                internal_bearer_token: (!arc_config.corestore_internal_bearer_token.is_empty())
                    .then(|| arc_config.corestore_internal_bearer_token.clone()),
            },
            if arc_config.requires_distributed_coremeta_recovery() {
                core_store::CoreStoreStartupRecovery::Distributed
            } else {
                core_store::CoreStoreStartupRecovery::Immediate
            },
        )
        .await?;
        let personaldb_signing_key_store =
            Arc::new(personaldb_signing_store::PersonalDbSigningKeyStore::new(
                core_store.clone(),
                secret_keyring.clone(),
            ));
        let personaldb_protocol_keyring = if has_personaldb_keyring_override {
            personaldb_protocol_keyring
        } else {
            match personaldb_signing_key_store.load_protocol_keyring() {
                Ok(keyring) => keyring,
                Err(error) => {
                    warn!(
                        error = %error,
                        "PersonalDB signing keys are unavailable; PersonalDB signing operations will fail closed"
                    );
                    personaldb_signing::PersonalDbProtocolKeyring::disabled()
                }
            }
        };
        let personaldb_protocol_keyring = Arc::new(personaldb_protocol_keyring);
        let persistence = persistence::Persistence::new(&arc_config)?;
        core_store.install_repair_task_scheduler(persistence.clone())?;
        if !arc_config.region.is_empty() && !arc_config.requires_distributed_coremeta_recovery() {
            // A standalone node owns its local region bootstrap. Distributed
            // regions are installed through the admin topology bootstrap and
            // recovered through CoreMeta; re-creating one on every process
            // start can observe a prepared-but-not-yet-recovered fence row.
            persistence
                .create_region(&arc_config.region)
                .await
                .context("bootstrap standalone region")?;
        }
        let sharder = sharding::ShardManager::new();
        let personaldb_commit_locks = Arc::new(Mutex::new(HashMap::new()));
        let native_mutation_locks = Arc::new(Mutex::new(HashMap::new()));
        let observability = observability::Observability::default();

        let bucket_manager =
            bucket_manager::BucketManager::new(persistence.clone(), storage.clone());
        let object_manager = object_manager::ObjectManager::new(
            persistence.clone(),
            storage.clone(),
            core_store.clone(),
            arc_config.region.clone(),
            arc_config.cross_region_routing_policy,
            partition_signing_key,
            observability.clone(),
        );
        if !core_store.startup_recovery_deferred() {
            system_realm::ensure_bootstrapped(
                &arc_config,
                &persistence,
                &storage,
                secret_keyring.as_ref(),
            )
            .await
            .context("bootstrap system realm")?;
        }

        Ok(Self {
            persistence,
            storage,
            core_store,
            sharder,
            jwt_manager,
            region: arc_config.region.clone(),
            bucket_manager,
            object_manager,
            config: arc_config,
            secret_keyring,
            personaldb_signing_key_store,
            personaldb_protocol_keyring,
            personaldb_commit_locks,
            native_mutation_locks,
            observability,
        })
    }

    pub async fn ensure_system_realm_bootstrapped(&self) -> Result<()> {
        system_realm::ensure_bootstrapped(
            &self.config,
            &self.persistence,
            &self.storage,
            self.secret_keyring.as_ref(),
        )
        .await
        .context("bootstrap system realm")
    }
}

#[cfg(test)]
mod app_state_tests {
    use super::*;

    #[tokio::test]
    async fn starts_without_personaldb_signing_keys() {
        let directory = tempfile::tempdir().unwrap();
        let config = Config {
            jwt_secret: "test-secret".to_string(),
            anvil_secret_encryption_key:
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string(),
            public_api_addr: "127.0.0.1:0".to_string(),
            api_listen_addr: "127.0.0.1:0".to_string(),
            region: "local".to_string(),
            bootstrap_system_admin_subject_kind: "app".to_string(),
            bootstrap_system_admin_subject_id: "admin-principal".to_string(),
            storage_path: directory
                .path()
                .join("storage")
                .to_string_lossy()
                .into_owned(),
            ..Config::default()
        };

        let state = AppState::new(
            config,
            personaldb_signing::PersonalDbProtocolKeyring::disabled(),
        )
        .await
        .unwrap();

        assert!(!state.personaldb_protocol_keyring.is_enabled());
        assert!(
            state
                .personaldb_signing_key_store
                .list_public_records()
                .unwrap()
                .is_empty()
        );
    }

    #[tokio::test]
    async fn distributed_startup_leaves_region_creation_to_topology_bootstrap() {
        let directory = tempfile::tempdir().unwrap();
        let config = Config {
            jwt_secret: "test-secret".to_string(),
            anvil_secret_encryption_key:
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa".to_string(),
            public_api_addr: "127.0.0.1:0".to_string(),
            api_listen_addr: "127.0.0.1:0".to_string(),
            region: "distributed-region".to_string(),
            bootstrap_system_admin_subject_kind: "app".to_string(),
            bootstrap_system_admin_subject_id: "admin-principal".to_string(),
            bootstrap_node_ids: vec!["node-a".to_string(), "node-b".to_string()],
            storage_path: directory
                .path()
                .join("storage")
                .to_string_lossy()
                .into_owned(),
            ..Config::default()
        };

        let state = AppState::new(
            config,
            personaldb_signing::PersonalDbProtocolKeyring::disabled(),
        )
        .await
        .unwrap();

        assert!(state.persistence.list_regions().await.unwrap().is_empty());
    }
}
